import type { NextPage } from 'next';
import Head from 'next/head';
import Blog from '../components/Blog';
import Contact from '../components/Contact';
import Heading from '../components/Heading';
import Infos from '../components/Infos';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
      <Infos />
      <Blog />
      <Contact />
    </div>
  );
};

export default Home;
