import type { NextPage } from 'next';
import Head from 'next/head';
import Heading from '../components/Heading';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
    </div>
  );
};

export default Home;
